### ISSUE TITLE
Doesn't Compile on Manjaro

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [superboubek/QMVC#1]
In file included from CageManip.h:60,
                 from main.cpp:29:
CageManipInterface.h: In member function ‘std::vector<std::vector<int> >& CMInterface<point_t>::get_cage_quads_cuts()’:
CageManipInterface.h:173:79: error: invalid initialization of reference of type ‘std::vector<std::vector<int> >&’ from expression of type ‘std::vector<std::pair<int, int> >’
     inline std::vector< std::vector< int > > & get_cage_quads_cuts() { return cage_quads_cuts ; }
                                                                               ^~~~~~~~~~~~~~~
CageManipInterface.h: In member function ‘const std::vector<std::vector<int> >& CMInterface<point_t>::get_cage_quads_cuts() const’:
CageManipInterface.h:174:91: error: invalid initialization of reference of type ‘const std::vector<std::vector<int> >&’ from expression of type ‘const std::vector<std::pair<int, int> >’
     inline std::vector< std::vector< int > > const & get_cage_quads_cuts() const { return cage_quads_cuts ; }
                                                                                           ^~~~~~~~~~~~~~~
In file included from main.cpp:29:
CageManip.h: In member function ‘void CMViewer::pickBackgroundColor()’:
CageManip.h:533:19: error: ‘class CMViewer’ has no member named ‘updateGL’; did you mean ‘update’?
             this->updateGL();
                   ^~~~~~~~
                   update
CageManip.h: In member function ‘virtual void CMViewer::init()’:
CageManip.h:597:29: error: ‘class QSurfaceFormat’ has no member named ‘setSampleBuffers’; did you mean ‘setSamples’?
         context()->format().setSampleBuffers(true);
                             ^~~~~~~~~~~~~~~~
                             setSamples
CageManip.h: In member function ‘virtual void CMViewer::mousePressEvent(QMouseEvent*)’:
CageManip.h:716:17: error: ‘updateGL’ was not declared in this scope
                 updateGL();
                 ^~~~~~~~
CageManip.h:716:17: note: suggested alternative: ‘update’
                 updateGL();
                 ^~~~~~~~
                 update
CageManip.h: In member function ‘virtual void CMViewer::mouseMoveEvent(QMouseEvent*)’:
CageManip.h:735:17: error: ‘updateGL’ was not declared in this scope
                 updateGL();
                 ^~~~~~~~
CageManip.h:735:17: note: suggested alternative: ‘update’
                 updateGL();
                 ^~~~~~~~
                 update
CageManip.h: In member function ‘virtual void CMViewer::mouseReleaseEvent(QMouseEvent*)’:
CageManip.h:754:17: error: ‘updateGL’ was not declared in this scope
                 updateGL();
                 ^~~~~~~~
CageManip.h:754:17: note: suggested alternative: ‘update’
                 updateGL();
                 ^~~~~~~~
                 update
CageManip.h: In member function ‘void CMViewer::openCameraFromFile(const QString&)’:
CageManip.h:801:9: error: ‘updateGL’ was not declared in this scope
         updateGL();
         ^~~~~~~~
CageManip.h:801:9: note: suggested alternative: ‘update’
         updateGL();
         ^~~~~~~~
         update
CageManip.h: In member function ‘void CMViewer::open_mesh()’:
CageManip.h:827:13: error: ‘updateGL’ was not declared in this scope
             updateGL();
             ^~~~~~~~
CageManip.h:827:13: note: suggested alternative: ‘update’
             updateGL();
             ^~~~~~~~
             update
CageManip.h: In member function ‘void CMViewer::open_cage()’:
CageManip.h:893:13: error: ‘updateGL’ was not declared in this scope
             updateGL();
             ^~~~~~~~
CageManip.h:893:13: note: suggested alternative: ‘update’
             updateGL();
             ^~~~~~~~
             update
CageManip.h: In member function ‘void CMViewer::open_deformed_cage()’:
CageManip.h:913:13: error: ‘updateGL’ was not declared in this scope
             updateGL();
             ^~~~~~~~
CageManip.h:913:13: note: suggested alternative: ‘update’
             updateGL();
             ^~~~~~~~
             update
CageManip.h: In member function ‘void CMViewer::methodChanged(int)’:
CageManip.h:965:9: error: ‘updateGL’ was not declared in this scope
         updateGL();
         ^~~~~~~~
CageManip.h:965:9: note: suggested alternative: ‘update’
         updateGL();
         ^~~~~~~~
         update
In file included from CageManip.h:51,
                 from main.cpp:29:
shared/gl/TextureHandler.h: In instantiation of ‘void ScalarTextureHandler::initTexture(glViewer*, const QString&) [with glViewer = CMViewer]’:
CageManip.h:568:40:   required from here
shared/gl/TextureHandler.h:47:27: error: ‘class CMViewer’ has no member named ‘convertToGLFormat’
         textimg = viewer->convertToGLFormat( buf );
                   ~~~~~~~~^~~~~~~~~~~~~~~~~
shared/gl/TextureHandler.h:53:30: error: ‘class CMViewer’ has no member named ‘bindTexture’; did you mean ‘glBindTexture’?
         ui_text_id = viewer->bindTexture( textimg, GL_TEXTURE_2D, GL_RGB );
                      ~~~~~~~~^~~~~~~~~~~
                      glBindTexture
In file included from ../coordinates/shared/point3.h:58,
                 from CageManip.h:48,
                 from main.cpp:29:
shared/gl/openglincludeQtComp.h: At global scope:
shared/gl/openglincludeQtComp.h:64:12: warning: ‘int printOglError(const char*, int)’ defined but not used [-Wunused-function]
 static int printOglError (const char * file, int line) {
            ^~~~~~~~~~~~~
make: *** [Makefile:890: tmp/obj/main.o] Error 1

**Comment by Serbipunk** [comment]
maybe it is late but QMVC works well on my Ubuntu 18.04

![qmvc](https://user-images.githubusercontent.com/12607834/125884260-ab483440-2a98-48e6-9f72-97ddd01a94f4.png)

3rd-parties I have installed
```
sudo apt install libgsl-dev
sudo apt install libqglviewer-dev-qt5
```

**Comment by AcccGO** [comment]
> In file included from CageManip.h:60,
> from main.cpp:29:
> CageManipInterface.h: In member function ‘std::vector<std::vector >& CMInterface<point_t>::get_cage_quads_cuts()’:
> CageManipInterface.h:173:79: error: invalid initialization of reference of type ‘std::vector<std::vector >&’ from expression of type ‘std::vector<std::pair<int, int> >’
> inline std::vector< std::vector< int > > & get_cage_quads_cuts() { return cage_quads_cuts ; }
> ^~~~~~~~~~~~~~~
> CageManipInterface.h: In member function ‘const std::vector<std::vector >& CMInterface<point_t>::get_cage_quads_cuts() const’:
> CageManipInterface.h:174:91: error: invalid initialization of reference of type ‘const std::vector<std::vector >&’ from expression of type ‘const std::vector<std::pair<int, int> >’
> inline std::vector< std::vector< int > > const & get_cage_quads_cuts() const { return cage_quads_cuts ; }
> ^~~~~~~~~~~~~~~
> In file included from main.cpp:29:
> CageManip.h: In member function ‘void CMViewer::pickBackgroundColor()’:
> CageManip.h:533:19: error: ‘class CMViewer’ has no member named ‘updateGL’; did you mean ‘update’?
> this->updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘virtual void CMViewer::init()’:
> CageManip.h:597:29: error: ‘class QSurfaceFormat’ has no member named ‘setSampleBuffers’; did you mean ‘setSamples’?
> context()->format().setSampleBuffers(true);
> ^~~~~~~~~~~~~~~~
> setSamples
> CageManip.h: In member function ‘virtual void CMViewer::mousePressEvent(QMouseEvent*)’:
> CageManip.h:716:17: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:716:17: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘virtual void CMViewer::mouseMoveEvent(QMouseEvent*)’:
> CageManip.h:735:17: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:735:17: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘virtual void CMViewer::mouseReleaseEvent(QMouseEvent*)’:
> CageManip.h:754:17: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:754:17: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘void CMViewer::openCameraFromFile(const QString&)’:
> CageManip.h:801:9: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:801:9: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘void CMViewer::open_mesh()’:
> CageManip.h:827:13: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:827:13: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘void CMViewer::open_cage()’:
> CageManip.h:893:13: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:893:13: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘void CMViewer::open_deformed_cage()’:
> CageManip.h:913:13: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:913:13: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> CageManip.h: In member function ‘void CMViewer::methodChanged(int)’:
> CageManip.h:965:9: error: ‘updateGL’ was not declared in this scope
> updateGL();
> ^~~~~~~~
> CageManip.h:965:9: note: suggested alternative: ‘update’
> updateGL();
> ^~~~~~~~
> update
> In file included from CageManip.h:51,
> from main.cpp:29:
> shared/gl/TextureHandler.h: In instantiation of ‘void ScalarTextureHandler::initTexture(glViewer*, const QString&) [with glViewer = CMViewer]’:
> CageManip.h:568:40: required from here
> shared/gl/TextureHandler.h:47:27: error: ‘class CMViewer’ has no member named ‘convertToGLFormat’
> textimg = viewer->convertToGLFormat( buf );
> ~~~~~~~~^~~~~~~~~~~~~~~~~
> shared/gl/TextureHandler.h:53:30: error: ‘class CMViewer’ has no member named ‘bindTexture’; did you mean ‘glBindTexture’?
> ui_text_id = viewer->bindTexture( textimg, GL_TEXTURE_2D, GL_RGB );
> ~~~~~~~~^~~~~~~~~~~
> glBindTexture
> In file included from ../coordinates/shared/point3.h:58,
> from CageManip.h:48,
> from main.cpp:29:
> shared/gl/openglincludeQtComp.h: At global scope:
> shared/gl/openglincludeQtComp.h:64:12: warning: ‘int printOglError(const char*, int)’ defined but not used [-Wunused-function]
> static int printOglError (const char * file, int line) {
> ^~~~~~~~~~~~~
> make: *** [Makefile:890: tmp/obj/main.o] Error 1

I have met the same problem. Do you have any solution now?
